# Generated by Django 5.0.2 on 2024-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=None, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
